fixup! Fix #330: Display quick stats 📊
Try to fix tests that used to depend on "real history from shell":

    test stats_generator::tests::empty_history ... FAILED
    test stats_generator::tests::full_history ... FAILED
    test stats_generator::tests::partial_history ... FAILED

    failures:

    ---- stats_generator::tests::empty_history stdout ----
    McFly: Importing shell history for the first time. This may take a minute or two...thread 'stats_generator::tests::empty_history' panicked at src/shell_history.rs:62:17:
    McFly error: Please ensure HISTFILE or MCFLY_HISTFILE is set for your shell (environment variable not found)